### ISSUE TITLE
`PermissionError`: Pystow issues in ODK container

### ISSUE THREAD

**Issue by joeflack4** [INCATools/ontology-access-kit#416] opened 2022-12-16 22:03 UTC
## Overview
I am trying to our slurp that was previously succeeding, but after a recent OAK release, it no longer works. It looks like Docker is trying to install `oaklib`, and it fails there.

## Error
`ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/.local'
Check the permissions.`

[log.txt](https://github.com/INCATools/ontology-access-kit/files/10249722/log.txt)

## Possible solutions
a. Ditch pystow for some other caching method.
b. Can pystow cache stuff somewhere else that would alleviate the issue? Such as within the virtual environment, rather than a user data directory?
c. Provide the user some way to put in the directory (not sure if this will work if failing on pip install)

## Additional info
I don't think the details of the command are needed here, as it seems to be failing on `pip install`. But FYI, in `mondo-ingest`, from `src/ontology/`, I'm running `export ODK_TAG=dev; sh run.sh make slurp/ordo.tsv` ([source](https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/mondo-ingest.Makefile#L366)).

Nico had some comments here: https://github.com/cthoyt/pystow/issues/10

**Comment by joeflack4** [comment] 2022-12-16 22:04
@matentzn I meant to make this issue a week ago. I don't know if @cmungall did something to upgrade `oaklib`, but I'm no longer getting this error, so I'm going to close. Can you reopen if it's still an issue for you?

**Comment by cmungall** [comment] 2022-12-17 22:29
Did you mean to make an issue in this repo? This looks like it relates to another project.

I'm closing this for now, but if you think this is an OAK issue, make a new issue describing steps to reproduce the problem.

**Closed by cmungall** 2022-12-17 22:29 UTC

**Comment by joeflack4** [comment] 2022-12-18 00:35
@cmungall Yes, Nico asked me to open this issue here. I'm not sure when OAK added PyStow, but this ODK `PermissionError` issue has been happening to us ever since, and it appears to fail on installing `oaklib`.

As for solutions, (b) and (c) may be possible for OAK to do if PyStow is highly configurable, and depending on how `oaklib`'s installation works, but I don't know enough to say. My guess is probably not, but I wanted to throw them out there anyway.

**Comment by matentzn** [comment] 2022-12-18 04:33
The problem was that pystow tried to write .data into a directory somewhere that was not writable. Maybe that is not a problem anymore.

**Comment by cmungall** [comment] 2022-12-18 17:34
Yes pystow assumes by default a particular location. Maybe here we want a
new issue for an enhancement to allow pystow to be globally configured?

For now of course you can mount ~/.data

**Comment by cmungall** [comment] 2022-12-18 17:38
Oh I see you already filed an issue https://github.com/cthoyt/pystow/issues/10

I guess unless this is fixed the options are to mount or implement a more configurable pystow like mechanism in OAK?/semsql? I don't think that would be so hard we don't need most of the pystow functionality. But it probably wouldn't be hard to make a PR on pystow either

**Comment by cmungall** [comment] 2022-12-18 17:43
You do want to think about your overall strategy here. The ready made SQLite files are potentially large. You might want to be in more control of when they are downloaded, where they cached, when they are refreshed. This sounds like a data ops thing upstream of oak. Eg have your pipeline download the SQLite, deploy it somewhere visible in the docker container, and then just point to the .db file when running oak. This bypasses pystow

**Comment by matentzn** [comment] 2022-12-19 07:03
I dont have any opinions on this matter beyond the fact that oak shouldn't fail hard when `~/` happens to not be writable. In all of my use cases, where oak is a part of the make workflow, I do not need anyone to cache my intermediates - I do that myself!

**Comment by cmungall** [comment] 2022-12-19 17:17
The alternative to failing hard is to do something clever, or to make opinionated choices. For example "hmm, I seem to be unable to cache this, therefore I am going to do a fresh download each time". Or: "I am going to cycle through some alternative choices of where to cache this". IMO these are bad options as they lead to unexpected hard to debug behavior.

I am a huge proponent of hard fail with informative errors vs silent magic (provided the hard fail is caused by a genuine issue the framework is not expected to solve, e.g. parse error, network error, permission error in a documented location)

We do need the errors to be more informative. Solving this kind of thing in the general case is hard though.

It's hard to anticipate all exceptions thrown by any external library (reuse is good but it increase the attack surface area for unexpected things)

it's hard to handle all exceptions gracefully. Developers complain if there is insufficient information in the error message. Non-developers complain when given large geeky stacktraces. We give people the option of how much information to show with `--stacktrace` and `-v` and `-vv` etc but people get surprised if the default is different from what they would have chosen.

**Comment by joeflack4** [comment] 2022-12-22 21:30
Thanks for these thoughts and suggestions, Chris. It looks like Nico was able to resolve this. I checked the git diff on `run.sh`. Maybe I'm looking in the wrong place. Still not seeing that he did it, but glad it's been done.

**Comment by matentzn** [comment] 2022-12-22 21:40
The problem was that I was trying to use my Unix user inside the docker container, and that Unix user does not have a home directory inside the docket container.

**Comment by joeflack4** [comment] 2022-12-22 21:51
I understand that, but I just don't know what you changed to fix that. Not critical that I need to know those details though

**Comment by matentzn** [comment] 2022-12-23 06:26
Look at contents of run.sh file: I simply removed the -u parameter from the docker run command.

**Comment by cthoyt** [comment] 2023-01-13 19:58
I'm not sure what the issue is here, PyStow can be globally configured in one of several ways: https://github.com/cthoyt/pystow#%EF%B8%8F%EF%B8%8F-configuration. Are none of these options sufficient?

I noticed that these aren't included in the readthedocs so i will update that
